# graphql/queries.graphql

query GetTournaments {
    tournaments {
        id
        name
        season
    }
}

query GetClubs {
    clubs {
        id
        name
        region
        address
        contact_info
        website
    }
}

query GetClubsWithTeams {
    clubs {
        id
        name
        region
        teams {
            id
            name
        }
    }
}

query GetClub($id: ID!) {
    club(id: $id) {
        id
        name
        region
        address
        teams {
            id
            name
        }
    }
}

query GetClubMembers($id: ID!) {
    club(id: $id) {
        id
        members {
            id
            name
            email
        }
    }
}

query GetUsers {
    users {
        id
        name
        email
    }
}

mutation CreateClub($name: String!, $address: String!, $region: String!, $managerEmail: String!) {
    createClub(name: $name, address: $address, region: $region, managerEmail: $managerEmail) {
        id
        name
        region
        address
    }
}

mutation CreateTeam($name: String!, $clubId: Int!, $memberIds: [Int!]!) {
    createTeam(name: $name, clubId: $clubId, memberIds: $memberIds) {
        id
        name
    }
}
