# graphql/queries.graphql

query GetTournaments {
    tournaments {
        id
        name
        season
    }
}

query GetClubs($includeInactive: Boolean = false) {
    clubs(includeInactive: $includeInactive) {
        id
        name
        isActive
        region
        address
        contact_info
        website
    }
}

query GetClubsWithTeams($includeInactive: Boolean = false) {
    clubs(includeInactive: $includeInactive) {
        id
        name
        isActive
        region
        teams(includeInactive: $includeInactive) {
            id
            name
            isActive
        }
    }
}

query GetClub($id: ID!, $includeInactive: Boolean = false) {
    club(id: $id, includeInactive: $includeInactive) {
        id
        name
        isActive
        region
        address
        teams(includeInactive: $includeInactive) {
            id
            name
            isActive
        }
    }
}

query GetClubMembers($id: ID!, $includeInactive: Boolean = false) {
    club(id: $id, includeInactive: $includeInactive) {
        id
        members {
            id
            name
            email
        }
    }
}

query GetTeamForEdit($id: ID!, $includeInactive: Boolean = false) {
    team(id: $id, includeInactive: $includeInactive) {
        id
        name
        isActive
        club {
            id
            name
            isActive
            members {
                id
                name
                email
            }
        }
        members {
            id
            name
            email
        }
    }
}

query GetUsers {
    users {
        id
        name
        email
    }
}

mutation CreateClub($name: String!, $address: String!, $region: String!, $managerEmail: String!) {
    createClub(name: $name, address: $address, region: $region, managerEmail: $managerEmail) {
        id
        name
        region
        address
    }
}

mutation UpdateClub($id: Int!, $name: String, $address: String, $region: String) {
    updateClub(id: $id, name: $name, address: $address, region: $region) {
        id
        name
        region
        address
    }
}

mutation DeleteClub($id: Int!) {
    deleteClub(id: $id)
}

mutation CreateTeam($name: String!, $clubId: Int!, $memberIds: [Int!]!) {
    createTeam(name: $name, clubId: $clubId, memberIds: $memberIds) {
        id
        name
    }
}

mutation UpdateTeam($id: Int!, $name: String, $memberIds: [Int!]) {
    updateTeam(id: $id, name: $name, memberIds: $memberIds) {
        id
        name
    }
}

mutation DeleteTeam($id: Int!) {
    deleteTeam(id: $id)
}
