name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'rapport/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'rapport/**'
    types:
      - opened
      - synchronize
      - reopened
jobs:
  frontend:
    name: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "frontend"
  backend:
    name: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "backend"
  rapport:
    name: rapport
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended biber make
      - name: Compile LaTeX
        working-directory: rapport/latex-rapport
        run: |
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rapport-PDF
          path: rapport/latex-rapport/main.pdf
          retention-days: 30

